# -*- coding: utf-8 -*-
"""options.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnERUDnXmbwb7pGvCzYW6Q-Yq422cEmh
"""

import math
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np

"""**Exercise#1: Futures & Forwards**"""

def forward_payoff(ST, F0, position="long"):
    return ST - F0 if position == "long" else F0 - ST

F0 = 100  # forward price

prices = [80, 100, 120]

# Create empty lists to store payoffs
long_payoffs = []
short_payoffs = []

print("LONG position (buyer):")
for ST in prices:
    payoff = forward_payoff(ST, F0, "long")
    long_payoffs.append(payoff)
    print(f" At S_T = ${ST}, the Payoff = ${payoff}")

print("\nSHORT position (seller):")
for ST in prices:
    payoff = forward_payoff(ST, F0, "short")
    short_payoffs.append(payoff)  # ← ADD THIS (store the value)
    print(f" At S_T = ${ST}, the Payoff = ${payoff}")

# Graph - now using the lists we created
plt.figure(figsize=(8, 5))
plt.plot(prices, long_payoffs, label="Long (Buyer)", linewidth=2, color="blue", marker='o')
plt.plot(prices, short_payoffs, label="Short (Seller)", linewidth=2, color="red", marker='o')
plt.axhline(y=0, color="black", linestyle="-", linewidth=0.5)  # Zero line
plt.axvline(x=F0, color="gray", linestyle="--", linewidth=0.5)  # Forward price line
plt.xlabel("Market Price at Expiration (S_T)", fontsize=12)
plt.ylabel("Payoff", fontsize=12)
plt.title("Forward Contract Payoff (F₀ = $100)", fontsize=14)
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""**Exercise # 2: Black Scholes Pricing**"""

def bs_call(S, K, r, sigma, T):
    d1 = (np.log(S/K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

def bs_put(S, K, r, sigma, T):
    call = bs_call(S, K, r, sigma, T)
    return call - S + K * np.exp(-r * T)


call_price = bs_call(100, 100, 0.05, 0.20, 1)
put_price = bs_put(100, 100, 0.05, 0.20, 1)

print(f"Call Price = ${call_price:.2f}")
print(f"Put Price = ${put_price:.2f}")

# Verify put-call parity
print(f"\nPut-Call Parity Verification:")
print(f"C + K*e^(-rT) = {call_price:.2f} + {K * np.exp(-r * T):.2f} = {call_price + K * np.exp(-r * T):.2f}")
print(f"P + S = {put_price:.2f} + {S} = {put_price + S:.2f}")